Repository rohitagr0310/dw-code, pull requests merged in 2023-10, with the labels that each got.

#5 Basic window has been created and text editor iss refined
  __pycache__/menu_bar.cpython-311.pyc
  app.cpp
  base_window.py
  tasks.json
Labels: enhancement, hacktoberfest-accepted

#6 Menu bar
  .vscode/c_cpp_properties.json
  .vscode/launch.json
  .vscode/settings.json
  __pycache__/menu_bar.cpython-311.pyc
  base_window.py
  menu_bar.py
Labels: enhancement, hacktoberfest-accepted

#9 Update README.md
  README.md
Labels: documentation, hacktoberfest-accepted

#11 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: enhancement, hacktoberfest-accepted

#14 Update README.md
  README.md
Labels: documentation, enhancement, hacktoberfest-accepted

#17 Create TODO.md
  TODO.md
Labels: documentation, hacktoberfest-accepted

#15 Update README.md
  README.md
Labels: documentation, hacktoberfest-accepted

#19 Create requirements.txt
  requirements.txt
Labels: documentation, hacktoberfest-accepted

#21 Update README.md
  README.md
Labels: documentation, hacktoberfest-accepted

#22 documentation updated
  README.md
  __pycache__/menu_bar.cpython-311.pyc
  main.py
Labels: documentation, hacktoberfest-accepted

#25 line number in editor
  __pycache__/code_editor.cpython-311.pyc
  __pycache__/line_numbers.cpython-311.pyc
  __pycache__/menu_bar.cpython-311.pyc
  code_editor.py
  main.py
Labels: enhancement, hacktoberfest-accepted
